services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: schoolit_user
      POSTGRES_PASSWORD: schoolit_password
      POSTGRES_DB: schoolit_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
