import { Injectable, ForbiddenException } from '@nestjs/common';
import { PrismaService } from '../prisma.service';

@Injectable()
export class ChatService {
  constructor(private prisma: PrismaService) { }

  async createRoom(user1Id: number, user2Id: number, jobId?: number) {
    // Check if room exists
    const existing = await this.prisma.chatRoom.findFirst({
      where: {
        AND: [
          { users: { some: { id: user1Id } } },
          { users: { some: { id: user2Id } } },
          jobId ? { jobId } : {},
        ],
      },
    });

    if (existing) {
      return existing;
    }

    return this.prisma.chatRoom.create({
      data: {
        jobId,
        users: {
          connect: [{ id: user1Id }, { id: user2Id }],
        },
      },
    });
  }

  async getMyRooms(userId: number) {
    return this.prisma.chatRoom.findMany({
      where: {
        users: { some: { id: userId } },
      },
      include: {
        users: {
          where: {
            id: { not: userId },
          },
          select: {
            id: true,
            name: true,
            email: true,
            role: true,
            schoolProfile: { select: { schoolName: true, logoImage: true } },
            teacherProfile: { select: { profileImage: true, bio: true } },
          },
        },
        messages: {
          orderBy: { createdAt: 'desc' },
          take: 1,
        },
      },
      orderBy: { createdAt: 'desc' },
    });
  }

  async getMessages(roomId: number, userId: number) {
    const room = await this.prisma.chatRoom.findFirst({
      where: { id: roomId, users: { some: { id: userId } } },
    });
    if (!room) throw new ForbiddenException('Access denied');

    return this.prisma.chatMessage.findMany({
      where: { chatRoomId: roomId },
      orderBy: { createdAt: 'asc' },
      include: {
        sender: { select: { id: true, name: true } },
      },
    });
  }

  async sendMessage(roomId: number, senderId: number, content: string) {
    const room = await this.prisma.chatRoom.findUnique({
      where: { id: roomId },
      include: { users: { select: { id: true } } },
    });

    if (!room || !room.users.some((u) => u.id === senderId)) {
      throw new ForbiddenException('Access denied');
    }

    return this.prisma.chatMessage.create({
      data: {
        chatRoomId: roomId,
        senderId,
        content,
      },
      include: {
        sender: { select: { id: true, name: true } },
      },
    });
  }

  async getUserRooms(userId: number) {
    return this.prisma.chatRoom.findMany({
      where: { users: { some: { id: userId } } },
      select: { id: true },
    });
  }

  async markAsRead(roomId: number, userId: number) {
    const room = await this.prisma.chatRoom.findUnique({
      where: { id: roomId },
      include: { users: { select: { id: true } } },
    });

    if (!room || !room.users.some((u) => u.id === userId)) {
      throw new ForbiddenException('Access denied');
    }

    // Mark all messages in this room that were NOT sent by this user as read
    await this.prisma.chatMessage.updateMany({
      where: {
        chatRoomId: roomId,
        senderId: { not: userId },
        read: false,
      },
      data: { read: true },
    });

    return { success: true };
  }

  // Legal Audit: Export Chat for S2B/G2B Proof
  async exportChat(roomId: number, userId: number) {
    const room = await this.prisma.chatRoom.findFirst({
      where: { id: roomId, users: { some: { id: userId } } },
      include: {
        users: { select: { id: true, name: true, email: true, role: true } }
      }
    });

    if (!room) throw new ForbiddenException('Access denied');

    let jobTitle = 'General Inquiry';
    if (room.jobId) {
      const job = await this.prisma.jobListing.findUnique({
        where: { id: room.jobId },
        select: { title: true }
      });
      if (job) jobTitle = job.title;
    }

    const messages = await this.prisma.chatMessage.findMany({
      where: { chatRoomId: roomId },
      orderBy: { createdAt: 'asc' },
      include: { sender: { select: { name: true, email: true } } }
    });

    // Format for auditing
    const auditLog = {
      meta: {
        exportedAt: new Date(),
        requestedBy: userId,
        roomId: room.id,
        jobTitle: jobTitle,
        participants: room.users.map(u => `${u.name} (${u.role})`),
      },
      messages: messages.map(m => ({
        time: m.createdAt,
        sender: m.sender.name,
        content: m.content, // Preserved for anti-corruption audit
      })),
      disclaimer: "This log is generated by Schoolit for S2B/Administrative audit purposes. Content is immutable.",
    };

    return auditLog;
  }
}
